### ISSUE TITLE
Is using the executor necessary?

### ISSUE THREAD

**Issue by ntucker** [foo-software/lighthouse-check-orb#11]
I need to do some port forwarding and have my own image to make this work. I can't find any info on what's in `lighthouse-check/default`

**Comment by adamhenson** [comment]
Hi @ntucker - this project is completely open-source, so the info that your inquiring about is code that is completely accessible to the public. Per Orb convention you can find that definition [here](https://github.com/foo-software/lighthouse-check-orb/blob/master/src/executors/default.yml), the default registry being Dockerhub. I’ll save you a few clicks by linking the [Dockerfile](https://github.com/foo-software/lighthouse-check/blob/master/Dockerfile).

No, using that image isn’t completely necessary. But, the image should provide an environment capable of running Lighthouse and should have `@foo-software/lighthouse-check` installed.

Does that answer your question?

**Comment by ntucker** [comment]
Thanks for your reply, after learning more about Orbs I came to understand that the executor here is simply a docker image.
