### ISSUE TITLE
`TypeError: value.split is not a function` when using configFile

### ISSUE THREAD

**Issue by jahde** [foo-software/lighthouse-check-orb#8]
My team has been using the orb for our lighthouse audits over the past 2 months and it has worked great until this past week. On June 1, 2020 we started to notice the following lighthouse [failure](https://github.com/intercom/intercom/issues/175778):
```
/usr/lib/node_modules/@foo-software/lighthouse-check/dist/helpers/arguments.js:43
      value = value.split(',');
                    ^
TypeError: value.split is not a function
    at /usr/lib/node_modules/@foo-software/lighthouse-check/dist/helpers/arguments.js:43:21
```

We dynamically generate test urls and thought this might be the cause of the error. However, we confirmed that it was not the cause by configuring a test setup with normal urls (e.g. "www.foo.software").

It appears the issue only occurs when using the `configFile` pattern. We've tested adding the urls directly and that has no errors:
```
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - checkout
      - lighthouse-check/audit:
          urls: 'https://www.foo.software'
```

However, if we follow the same [configFile pattern](https://github.com/foo-software/website-performance-monitoring/blob/d212c458d4ba15b94fbc85234502bbb0dea82016/.circleci/config.yml#L28) with a `.json` file at the root folder then we notice the above error:
```
>config.yml
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - checkout
      - lighthouse-check/audit:
          configFile: lighthouse-config.json

>lighthouse-config.json
{
  "urls": ["https://www.foo.software"]
}

```

**Comment by adamhenson** [comment]
Thanks for reporting this @jahde. This issue is hopefully fixed with  foo-software/lighthouse-check#31. I also added a test for this case. The Orb uses the latest Docker image by default, so you should be able to just restart your job. Can you confirm the fix when you have time?

https://github.com/foo-software/lighthouse-check-orb/blob/4eef641da65087c63c99771976c7a224742c9b62/.circleci/config.yml#L38-L43

**Comment by sduquej** [comment]
@adamhenson I work with @jahde. Can confirm our workflow is now passing 🟢🟢🟢 

Thanks for the prompt release!

**Comment by adamhenson** [comment]
Amazing, 🙌 - feel free to report anything else in the future. And you can @ me when you open the issue. I've been having issues with receiving email notifications even though I'm watching this project and have the correct settings.
